[package]
name = "brinkokevin/config"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "default.project.json", "wally.toml", "LICENSE"]

[dependencies]
charm = "littensy/charm@0.11.0-rc.3"
